services:
  - type: web
    name: quodo3-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        value: gateway01.eu-central-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: 4000
      - key: DB_USER
        value: 4VmPGSU3EFyEhLJ.root
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: d_nothi_db
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://d-nothi-system-quodo3-all.vercel.app
      # Email Configuration (Optional - uncomment and set values if you want to enable email)
      # - key: EMAIL_HOST
      #   value: smtp.gmail.com
      # - key: EMAIL_PORT
      #   value: 587
      # - key: EMAIL_SECURE
      #   value: false
      # - key: EMAIL_USER
      #   sync: false
      # - key: EMAIL_PASS
      #   sync: false
      # - key: EMAIL_FROM
      #   value: "D-Nothi Team & Activity Management <no-reply@d-nothi.com>"

  - type: web
    name: quodo3-frontend
    runtime: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    envVars:
      - key: REACT_APP_API_URL
        value: https://quodo3-backend.onrender.com/api